config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /(#{I18n.available_locales.map(&:to_s).join('|')})/ do
    root "home#index"

    get "catalog",           to: "home#catalog"
    get "calculator",        to: "home#calculator"
    get "contacts",          to: "home#contacts"
    post "/contacts",        to: "home#create_request"
    get "products",          to: "home#products"
    get "product-page",      to: "home#product_page"
    get "alu-patio",         to: "home#alu_patio"
    get "alue-passive",      to: "home#alue_passive"
    get "alu-style",         to: "home#alu_style"
    get "alu-glass",         to: "home#alu_glass"
    get "glass",             to: "home#glass"
    get "blinds",            to: "home#blinds"
    get "alu-passive-doors", to: "home#alu_passive_doors"
    get "thank-you-request", to: "home#thankyou_request"

    devise_for :users
  end

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  mount MissionControl::Jobs::Engine, at: "/jobs"
end

app/views/layouts/_flash.html.slim
- flash.each do |key, msg|
  .notice__wrapper data-controller="flash"
    = content_tag :div, msg, class: key, data: { removals_target: "alert" }

app/views/layouts/_footer.html.slim
footer.footer
    .container
        .footer-wrapper
            .box.logo-box
                = link_to root_path, class: 'logo' do
                    = image_tag "icons/logo.png", alt: 'logo', title: 'logo', class: 'logo'
                .media-box
                    a.media-link href="https://www.instagram.com/hybrid.windows?igsh=MXZ4Nm1zMm53azJ2bg==" target="_blanc"
                        = image_tag  "icons/instagram.svg", title: 'icon', alt: 'icon'
                    a.media-link href="https://www.facebook.com/share/173Sr2ap8V/?mibextid=wwXIfr" target="_blanc"
                        = image_tag  "icons/facebook.svg", title: 'icon', alt: 'icon', class: 'facebook'
                    a.media-link href="https://www.tiktok.com/@hybrid.windows?_t=ZS-8zRNqEuXV1L&_r=1" target="_blanc"
                        = image_tag  "icons/tiktok.svg", title: 'icon', alt: 'icon', class: 'facebook'
            .box.line-box
                .line
                .title Контакти
                a.link href="tel:0632308665"
                    = image_tag "icons/phone.svg", title: 'icon', alt: 'icon', class: 'icon'
                    p 0 (63) 230 86 65
                a.link href="mailto:hybridwindows@gmail.com"
                    = image_tag "icons/email.svg", title: 'icon', alt: 'icon', class: 'icon'
                    p hybridwindows@gmail.com
                a.link href="https://maps.app.goo.gl/FbAhBg1FVQVSrYNw5" target="_blanc"
                    = image_tag "icons/location.svg", title: 'icon', alt: 'icon', class: 'icon'
                    p 8 Zlitna St., Sokilnyki, 81130, Lviv, Ukraine
            .box.line-box
                .line
                .title Сторінки
                = link_to "Продукти", products_path, class: "link #{'active' if current_page?(products_path)}"
                = link_to "Каталог", catalog_path, class: "link #{'active' if current_page?(catalog_path)}"
                = link_to "Калькулятор", calculator_path, class: "link #{'active' if current_page?(calculator_path)}"
                = link_to "Контакти", contacts_path, class: "link #{'active' if current_page?(contacts_path)}"
            .box.line-box
                .line
                .title Продукти
                = link_to "Вікна",               "/products#windows", class: 'link'
                = link_to "Двері",               "/alu-passive-doors", class: 'link'
                = link_to "Розсувні системи",    "/alu-patio", class: 'link'
                = link_to "Жалюзі у склопакеті", "/blinds", class: 'link'

app/views/layouts/_header.html.slim
header.header data-header-target="header"
    .container
        .header-wrapper
            .box
                = link_to "Продукти",    products_path, class: "#{'active' if current_page?(products_path)}"
                = link_to "Каталог",     catalog_path, class: "#{'active' if current_page?(catalog_path)}"
                = link_to "Калькулятор", calculator_path, class: "#{'active' if current_page?(calculator_path)}"
                = link_to "Про нас",     root_path(anchor: 'about-section')
            = link_to root_path, class: "logo" do
                = image_tag  "icons/logo.png", class: 'logo', alt: 'logo', title: 'logo'
            .box.right
                = link_to "0 (63) 230 86 65", "tel:0632308665"
                = link_to "Контакти", contacts_path, class: "#{'active' if current_page?(contacts_path)}"
            .box-buttons
                a.mobile-button href="#form-anchor" Залишити заявку
                .menu-button data-header-target="menuButton" data-action="click->header#toggleMenu"
                    .line
                    .line
                    .line
.mobile-nav-box data-header-target="mobileNav"
    = link_to "Продукти",    products_path, class: "#{'active' if current_page?(products_path)}"
    = link_to "Каталог",     catalog_path, class: "#{'active' if current_page?(catalog_path)}"
    = link_to "Калькулятор", calculator_path, class: "#{'active' if current_page?(calculator_path)}"
    = link_to "Про нас",     root_path(anchor: 'about-section'), data: { action: "click->header#toggleMenu" }
    = link_to "Контакти",    contacts_path, class: "#{'active' if current_page?(contacts_path)}"
    = link_to "0 (63) 230 86 65", "tel:0632308665"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = content_for(:title) || "HYBRID WINDOWS"
    meta name="viewport" content="width=device-width,initial-scale=1"
    meta name="apple-mobile-web-app-capable" content="yes"
    meta name="mobile-web-app-capable" content="yes"
    = csrf_meta_tags
    = csp_meta_tag
    = turbo_refreshes_with method: :morph, scroll: :preserve
    = yield :head
    = tag.link rel: "manifest", href: pwa_manifest_path(format: :json)
    link rel="icon" href="/favicon.png" type="image/png"
    link rel="icon" href="/favicon.png" type="image/svg+xml"
    link rel="apple-touch-icon" href="/favicon.png"
    meta name="turbo-visit-control" content="reload"
    meta name="turbo-cache-control" content="no-cache"


    = stylesheet_link_tag 'application', "data-turbo-track": "reload"
    = stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/swiper@11.2.2/swiper-bundle.min.css', "data-turbo-track": "reload"
    = javascript_importmap_tags
    <script src="https://js.hcaptcha.com/1/api.js" async defer></script>
    = favicon_link_tag 'favicon.png'

    / <script type="text/javascript">(function (d,s,u,e,p) {p=d.getElementsByTagName(s)[0],e=d.createElement(s),e.async=1,e.src=u,p.parentNode.insertBefore(e, p);})(document, 'script', 'https://script.ringostat.com/v4/2d/2da96835b7ae1cda47aa4edd8fb6cc1c6b2e7a3b.js');var pw = function() {if (typeof(ringostatAnalytics) === "undefined") {setTimeout(pw,100);} else {ringostatAnalytics.sendHit('pageview');}};pw();</script>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-WDP8HR3R');</script>

  body data-controller="header" data-turbo="false"
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WDP8HR3R" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    #flash
      = render 'layouts/flash'
    = render 'layouts/header'
    .page-content
      = yield
    = render 'layouts/footer'